/* eslint-disable import/prefer-default-export */
export const PUBLISHER_LIST = [
    'Elsevier',
    'Wiley',
    'MDPI',
    'Springer Nature',
    'Oxford University Press',
    'Japan Society Mechanical Engineers',
    'ACS',
    'Taylor & Francis',
    'Lippincott Williams & Wilkins',
    'APS',
    'Institute of Physics',
    'IEEE',
    'Royal Society of Chemistry',
    'IOP Publishing',
    'Frontiers Media',
    'SAGE',
    'American Institute of Physics',
    'PLOS',
    'The Japanese Society of Internal Medicine',
    'Springer International Publishing',
    'Japan Society of Applied Physics',
    'The Japanese Psychological Association',
    'Japanese Pharmacological Society',
    'The Japan Society of Mechanical Engineers',
    'Cambridge University Press',
    'BMJ',
    'Karger Publishers',
    'Institute of Electronics Information and Communication Engineers',
    'Architectural Institute of Japan',
    'Thieme Medical Publishers (Germany)',
    'American Association for Cancer Research',
    'Cureus Inc.',
    'Wolters Kluwer',
    'EDP Sciences',
    'Hindawi Publishing Corporation',
    'Pharmaceutical Society of Japan',
    'World Scientific',
    'Institute of Electrical Engineers of Japan',
    'Physical Society of Japan',
    'Optica Publishing Group',
];

export const REPOSITORY_LIST = {
    'All japanise repositories': 'ja-repository',
    'PubMed Central': 'PubMed Central',
    arXiv: 'arXiv (Cornell University)',
    'Europe PMC': 'Europe PMC (PubMed Central)',
    HAL: 'HAL (Le Centre pour la Communication Scientifique Directe)',
    'Research Square': 'Research Square (Research Square)',
    bioRxiv: 'bioRxiv (Cold Spring Harbor Laboratory)',
    'OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)': 'OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)',
    SSRN: 'SSRN Electronic Journal',
    RePEc: 'RePEc: Research Papers in Economics',
    'UCL Discovery (University College London)': 'UCL Discovery (University College London)',
    Authorea: 'Authorea (Authorea)',
    Zenodo: 'Zenodo (CERN European Organization for Nuclear Research)',
    DANS: 'Data Archiving and Networked Services (DANS)',
    'eScholarship (California Digital Library)': 'eScholarship (California Digital Library)',
    medRxiv: 'medRxiv (Cold Spring Harbor Laboratory)',
    'OPAL (La Trobe University)': 'OPAL (Open@LaTrobe) (La Trobe University)',
    MDPI: 'MDPI (MDPI AG)',
    'INDIGO (University of Illinois at Chicago)': 'INDIGO (University of Illinois at Chicago)',
    'University of Groningen research database': 'University of Groningen research database (University of Groningen / Centre for Information Technology)',
    'Radboud Repository (Radboud University)': 'Radboud Repository (Radboud University)',
    'PsyArXiv (OSF Preprints)': 'PsyArXiv (OSF Preprints)',
    'Lirias (KU Leuven)': 'Lirias (KU Leuven)',
    'DTU Orbit (Technical University of Denmark)': 'Technical University of Denmark, DTU Orbit (Technical University of Denmark, DTU)',
    'University of Birmingham Research Portal': 'University of Birmingham Research Portal (University of Birmingham)',
    'Duo Research Archive (University of Oslo)': 'Duo Research Archive (University of Oslo)',
    'Oxford University Research Archive': 'Oxford University Research Archive (ORA) (University of Oxford)',
};
