/* eslint-disable import/prefer-default-export */
export const PUBLISHER_LIST = [
  'Elsevier',
  'Wiley',
  'MDPI',
  'Springer Nature',
  'Oxford University Press',
  'Japan Society Mechanical Engineers',
  'ACS',
  'Taylor & Francis',
  'Lippincott Williams & Wilkins',
  'APS',
  'Institute of Physics',
  'IEEE',
  'Royal Society of Chemistry',
  'IOP Publishing',
  'Frontiers Media',
  'SAGE',
  'American Institute of Physics',
  'PLOS',
  'The Japanese Society of Internal Medicine',
  'Japan Society of Applied Physics',
  'The Japanese Psychological Association',
  'Japanese Pharmacological Society',
  'The Japan Society of Mechanical Engineers',
  'Cambridge University Press',
  'BMJ',
  'Karger Publishers',
  'Institute of Electronics, Information and Communication Engineers',
  'Architectural Institute of Japan',
  'Thieme Medical Publishers (Germany)',
  'American Association for Cancer Research',
  'Cureus, Inc.',
  'Wolters Kluwer',
  'EDP Sciences',
  'Hindawi Publishing Corporation',
  'Pharmaceutical Society of Japan',
  'World Scientific',
  'Institute of Electrical Engineers of Japan',
  'Physical Society of Japan',
  'Optica Publishing Group',
];

export const REPOSITORY_LIST = {
  'ja-repositories': 'ja-repository',
  'PubMed Central': 'PubMed Central',
  arXiv: 'arXiv (Cornell University)',
  'Europe PMC': 'Europe PMC (PubMed Central)',
  HAL: 'HAL (Le Centre pour la Communication Scientifique Directe)',
  'Research Square': 'Research Square (Research Square)',
  bioRxiv: 'bioRxiv (Cold Spring Harbor Laboratory)',
  'OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)': 'OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)',
  SSRN: 'SSRN Electronic Journal',
  RePEc: 'RePEc: Research Papers in Economics',
  'UCL Discovery (University College London)': 'UCL Discovery (University College London)',
  Authorea: 'Authorea (Authorea)',
  Zenodo: 'Zenodo (CERN European Organization for Nuclear Research)',
  DANS: 'Data Archiving and Networked Services (DANS)',
  'eScholarship (California Digital Library)': 'eScholarship (California Digital Library)',
  medRxiv: 'medRxiv (Cold Spring Harbor Laboratory)',
  'OPAL (La Trobe University)': 'OPAL (Open@LaTrobe) (La Trobe University)',
  MDPI: 'MDPI (MDPI AG)',
  'INDIGO (University of Illinois at Chicago)': 'INDIGO (University of Illinois at Chicago)',
  'University of Groningen research database': 'University of Groningen research database (University of Groningen / Centre for Information Technology)',
  'Radboud Repository (Radboud University)': 'Radboud Repository (Radboud University)',
  'PsyArXiv (OSF Preprints)': 'PsyArXiv (OSF Preprints)',
  'Lirias (KU Leuven)': 'Lirias (KU Leuven)',
  'DTU Orbit (Technical University of Denmark)': 'Technical University of Denmark, DTU Orbit (Technical University of Denmark, DTU)',
  'University of Birmingham Research Portal': 'University of Birmingham Research Portal (University of Birmingham)',
  'Duo Research Archive (University of Oslo)': 'Duo Research Archive (University of Oslo)',
  'Oxford University Research Archive': 'Oxford University Research Archive (ORA) (University of Oxford)',
};

export const EXCLUDE_REPOSITORIES_LIST = [
  'Asahikawa Medical University Collection and Research (Asahikawa Medical University)',
  'Asia University Academic Repository (Asia University)',
  'Fukushima Medical University Repository (Fukushima Medical University)',
  'Future University Hakodate Academic Archive (Future University Hakodate)',
  'HamaMed-Repository (Hamamatsu University School of Medicine)',
  'Hirosaki University Repository for Academic Resources (Hirosaki University)',
  'Hiroshima Associated Repository Portal (Hiroshima University)',
  'Hiroshima University Acedemic Information Repository (Hiroshima University)',
  'Hokkaido University Collection of Scholarly and Academic Papers (Hokkaido University)',
  'Hosei University Repository (Hosei University)',
  'Institutional Resources for Unique Collection and Academic Archives (Tokyo Dental College)',
  'Iwate Medical University Repository (Iwate Medical University)',
  'Iwate University Repository (Iwate University)',
  'Jaea Originated Papers Searching System (National Research and Development Corporation Japan Atomic Energy Agency)',
  'Japanese Red Cross Kyushu International College of Nursing Repository (Japanese Red Cross Kyushu International College of Nursing)',
  'JAXA Repository (JAXA)',
  'Josai University Repository of Academia (Josai University)',
  'Kanagawa Dental University Repository (Kanagawa Dental University)',
  'Kanagawa University Repository (Kanagawa University)',
  'Kanazawa University Repository for Academic Resources (DSpace) (Kanazawa University)',
  'Kansai University Institutional Repository (Kansai University)',
  'Kawasaki University of Medical Welfare Institutional Repository (Kawasaki University of Medical Welfare)',
  'Kobe City University of Foreign Studies Academic Information Center Repository (Kobe City University of Foreign Studies)',
  "Kobe Shoin Women\\'s University Repository (Kobe Shoin Women\\'s University)",
  'Kobe University Repository Kernel (Kobe University)',
  'Kochi University Digital Repository for Academic Resources (Kochi University)',
  'Kochi University of Technology Academic Resource Repository (Kochi University of Technology)',
  'Kumamoto University Repository (Kumamoto University)',
  'Kurume University Institutional Repository (Kurume University)',
  'Kyoto University Research Information Repository (Kyoto University)',
  'Kyushu University Institutional Repository (QIR) (Kyushu University)',
  'Kyushu University of Health and Welfare Repository (Kyushu University of Health and Welfare)',
  'Meiji Gakuin University Institutional Repository (Meiji Gakuin University)',
  'Meiji University of Integrative Medicine Academic Repository (Meiji University of Integrative Medicine)',
  'Meisei University Academic Institution Repository (Meisei University)',
  'Musashino University Academic Institutional Repository (Musashino University)',
  'Nagasaki International University Academic Institutional Repository (NIU-AIR) (Nagasaki International University)',
  "Nagasaki University\\'s Academic Output SITE (Nagasaki University)",
  'Nara Medical University Institutional Repository (GINMU) (Nara Medical University)',
  'Nara University of Education Academic Repository (Nara University of Education)',
  'National Institute for Fusion Science Repository (National Institute for Fusion Science)',
  'Niigata College of Nursing Repository (Niigata College of Nursing)',
  'Okayama University Scientific Achievement Repository (Okayama University)',
  'Okinawa Institute of Science and Technology Graduate University (Okinawa Institute of Science and Technology Graduate University)',
  'Osaka City University (Osaka City University)',
  'Osaka Prefecture University Repository (Osaka Prefecture University)',
  'Otemae University & Otemae College Repository (Otemae University and College)',
  'OUKA (Osaka University Knowledge Archive) (Osaka University)',
  'QIR (Kyushu University Institutional Repository) (Kyushu University)',
  'Rikkyo University academic repository (Rikko Roots) (Rikkyo University)',
  'Saitama Medical University Repository (Saitama Medical University)',
  'Shizuoka University Repository (Shizuoka University)',
  'SOAR (Shinshu University)',
  'Surugadai University Repository for Academic Resources (Surugadai University)',
  'Terrestrial Environment Research Center (University of Tsukuba)',
  'The Nippon Dental University Repository (The Nippon Dental University)',
  'Tokyo Gakugei University Repository (Tokyo Gakugei University)',
  'Tokyo Tech Research Repository (Tokyo Institute of Technology)',
  'Tottori University research result repository (Tottori University)',
  'Toyohashi University of Technology Academic Institutional Repository (Toyohashi University)',
  'University of Tokyo Repository (University of Tokyo)',
  'University of Toyama Repository for Academic Information (University of Toyama)',
  'Waseda University Repository (Waseda University)',
  'Yamagata University Academic Repository (Yamagata University)',
  'Yamaguchi University Navigator for Open Access Collection and Archives (Yamaguchi University)',
  'Yokohama National University Repository (Yokohama National University)',
  '岡山県立大学学術情報リポジトリ (Okayama Prefectural University)',
  '順天堂大学学術情報リポジトリ (Juntendo University)',
];
