export const graphIds = [
  'app.sante-publi.publishers.politiques-ouverture.chart-classement',
  'app.national-publi.publishers.politiques-ouverture.chart-classement',
  'app.sante-publi.disciplines.voies-ouverture.chart-repartition-publications',
  'app.national-publi.disciplines.voies-ouverture.chart-repartition-publications',
  'app.sante-publi.disciplines.voies-ouverture.chart-evolution-comparaison-types-hebergement',
  'app.national-publi.disciplines.voies-ouverture.chart-evolution-comparaison-types-hebergement',
  'app.sante-publi.affiliations.pays.chart-classement-pays',
  'app.national-publi.affiliations.pays.chart-classement-pays',
  'app.sante-publi.publishers.type-ouverture.chart-evolution-repartition',
  'app.national-publi.disciplines.voies-ouverture.chart-evolution-comparaison-types-hebergement',
  'app.sante-publi.disciplines.voies-ouverture.chart-evolution-comparaison-types-hebergement',
  'app.national-publi.publishers.type-ouverture.chart-evolution-repartition',
  'app.sante-publi.publishers.type-ouverture.chart-repartition-modeles',
  'app.national-publi.publishers.type-ouverture.chart-repartition-modeles',
  'app.sante-publi.general.dynamique-ouverture.chart-taux-ouverture',
  'app.national-publi.general.dynamique-ouverture.chart-taux-ouverture',
  'app.sante-publi.general.dynamique-ouverture.chart-evolution-proportion',
  'app.national-publi.general.dynamique-ouverture.chart-evolution-proportion',
  'app.sante-publi.general.voies-ouverture.chart-repartition-taux',
  'app.national-publi.general.voies-ouverture.chart-repartition-taux',
  'app.sante-publi.general.voies-ouverture.chart-evolution-taux',
  'app.national-publi.general.voies-ouverture.chart-evolution-taux',
  'app.sante-publi.general.voies-ouverture.chart-repartition-publications',
  'app.national-publi.general.voies-ouverture.chart-repartition-publications',
  'app.national-publi.general.genres-ouverture.chart-repartition-genres',
  'app.sante-publi.general.genres-ouverture.chart-repartition-genres',
  'app.sante-publi.general.langues-ouverture.chart-repartition-publications',
  'app.national-publi.general.langues-ouverture.chart-repartition-publications',
  'app.sante-publi.general.impact-financement.chart-taux-ouverture',
  'app.national-publi.general.impact-financement.chart-taux-ouverture',
  'app.sante-publi.general.impact-financement.chart-repartition-financements',
  'app.national-publi.general.impact-financement.chart-repartition-financements',
  'app.sante-publi.disciplines.voies-ouverture.chart-evolution-comparaison-types-hebergement',
  'app.national-publi.disciplines.voies-ouverture.chart-evolution-comparaison-types-hebergement',
  'app.sante-publi.affiliations.dynamique-ouverture.chart-evolution-proportion',
  'app.national-publi.affiliations.dynamique-ouverture.chart-evolution-proportion',
  'app.sante-publi.affiliations.pays.chart-taux-rang-utile',
  'app.national-publi.affiliations.pays.chart-taux-rang-utile',
  'app.sante-publi.publishers.dynamique-ouverture.chart-taux-ouverture',
  'app.national-publi.publishers.dynamique-ouverture.chart-taux-ouverture',
  'app.sante-publi.publishers.dynamique-ouverture.chart-evolution-proportion',
  'app.national-publi.publishers.dynamique-ouverture.chart-evolution-proportion',
  'app.sante-publi.affiliations.dynamique-ouverture.chart-taux-ouverture',
  'app.national-publi.affiliations.dynamique-ouverture.chart-taux-ouverture',
  'app.sante-publi.publishers.politiques-ouverture.chart-comparaison',
  'app.national-publi.publishers.politiques-ouverture.chart-comparaison',
  'app.national-publi.disciplines.dynamique-ouverture.chart-taux-ouverture',
  'app.sante-publi.disciplines.dynamique-ouverture.chart-taux-ouverture',
  'app.sante-publi.publishers.repartition-licences.chart-repartition',
  'app.national-publi.publishers.repartition-licences.chart-repartition',
  'app.sante-publi.publishers.repartition-licences.chart-classement',
  'app.national-publi.publishers.repartition-licences.chart-classement',
  'app.sante-publi.publishers.couts-publication.chart-depenses-estimees',
  'app.national-publi.publishers.couts-publication.chart-depenses-estimees',
  'app.sante-publi.publishers.couts-publication.chart-distribution',
  'app.national-publi.publishers.couts-publication.chart-distribution',
  'app.sante-publi.publishers.couts-publication.chart-distribution-par-annee',
  'app.national-publi.publishers.couts-publication.chart-distribution-par-annee',
  'app.sante-publi.repositories.dynamique-ouverture.chart-taux-ouverture',
  'app.national-publi.repositories.dynamique-ouverture.chart-taux-ouverture',
  'app.sante-publi.repositories.dynamique-ouverture.chart-evolution-proportion',
  'app.national-publi.repositories.dynamique-ouverture.chart-evolution-proportion',
  'app.sante-publi.repositories.plus-utilisees.chart-nombre-documents',
  'app.national-publi.repositories.plus-utilisees.chart-nombre-documents',
  'app.sante-publi.repositories.dynamique-depot.chart-nombre-documents-depots',
  'app.national-publi.repositories.dynamique-depot.chart-nombre-documents-depots',
  'app.sante-publi.repositories.dynamique-hal.chart-couverture-hal',
  'app.national-publi.repositories.dynamique-hal.chart-couverture-hal',
  'app.sante-publi.publishers.poids-revues.chart-repartition',
  'app.national-publi.publishers.poids-revues.chart-repartition',
  'app.sante-publi.disciplines.dynamique-ouverture.chart-evolution-taux-ouverture',
  'app.national-publi.disciplines.dynamique-ouverture.chart-evolution-taux-ouverture',
];

export const domains = ['health', ''];

export const mobileButtonLabel = {
  fr: {
    '/sante/publications/disciplines': 'app.publi.disciplines',
    '/sante/publications/affiliations': 'app.publi.affiliations',
    '/sante/publications/editeurs': 'app.publi.editeurs',
    '/sante/publications/general': 'app.publi.general',
    '/sante/publications/archives': 'app.publi.archives',
    '/sante/essais-cliniques': 'app.publi.general',
    '/publications/disciplines': 'app.publi.disciplines',
    '/publications/editeurs': 'app.publi.editeurs',
    '/publications/general': 'app.publi.general',
    '/publications/archives': 'app.publi.archives',
  },
  en: {
    '/health/publications/disciplines': 'app.publi.disciplines',
    '/health/publications/affiliations': 'app.publi.affiliations',
    '/health/publications/archives': 'app.publi.archives',
    '/health/publications/editeurs': 'app.publi.editeurs',
    '/health/publications/general': 'app.publi.general',
    '/publications/disciplines': 'app.publi.disciplines',
    '/publications/archives': 'app.publi.archives',
    '/publications/editeurs': 'app.publi.editeurs',
    '/publications/general': 'app.publi.general',
  },
};
